/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackIcon: typeof import('./src/components/BackIcon.vue')['default']
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
    BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
    BasePage: typeof import('./src/components/BasePage.vue')['default']
    Book: typeof import('./src/components/Book.vue')['default']
    Checkbox: typeof import('./src/components/base/checkbox/Checkbox.vue')['default']
    Close: typeof import('./src/components/icon/Close.vue')['default']
    DictGroup: typeof import('./src/components/list/DictGroup.vue')['default']
    DictList: typeof import('./src/components/list/DictList.vue')['default']
    Empty: typeof import('./src/components/Empty.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconEosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
    IconFluentAdd16Regular: typeof import('~icons/fluent/add16-regular')['default']
    IconFluentArrowCircleRight16Regular: typeof import('~icons/fluent/arrow-circle-right16-regular')['default']
    IconFluentArrowShuffle20Filled: typeof import('~icons/fluent/arrow-shuffle20-filled')['default']
    IconFluentArrowSwap20Regular: typeof import('~icons/fluent/arrow-swap20-regular')['default']
    IconFluentBookNumber20Filled: typeof import('~icons/fluent/book-number20-filled')['default']
    IconFluentCheckmarkCircle20Filled: typeof import('~icons/fluent/checkmark-circle20-filled')['default']
    IconFluentChevronLeft28Filled: typeof import('~icons/fluent/chevron-left28-filled')['default']
    IconFluentDismissCircle16Regular: typeof import('~icons/fluent/dismiss-circle16-regular')['default']
    IconFluentDismissCircle20Filled: typeof import('~icons/fluent/dismiss-circle20-filled')['default']
    IconFluentErrorCircle20Filled: typeof import('~icons/fluent/error-circle20-filled')['default']
    IconFluentEye16Regular: typeof import('~icons/fluent/eye16-regular')['default']
    IconFluentEyeOff16Regular: typeof import('~icons/fluent/eye-off16-regular')['default']
    IconFluentLockClosed20Regular: typeof import('~icons/fluent/lock-closed20-regular')['default']
    IconFluentMail20Regular: typeof import('~icons/fluent/mail20-regular')['default']
    IconFluentNumberSymbol20Regular: typeof import('~icons/fluent/number-symbol20-regular')['default']
    IconFluentPhone20Regular: typeof import('~icons/fluent/phone20-regular')['default']
    IconFluentSearch24Regular: typeof import('~icons/fluent/search24-regular')['default']
    IconFluentSlideTextTitleEdit20Regular: typeof import('~icons/fluent/slide-text-title-edit20-regular')['default']
    IconFluentStar20Filled: typeof import('~icons/fluent/star20-filled')['default']
    Progress: typeof import('./src/components/base/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Toast: typeof import('./src/components/base/toast/Toast.vue')['default']
    Tooltip: typeof import('./src/components/base/Tooltip.vue')['default']
  }
}

// For TSX support
declare global {
  const BackIcon: typeof import('./src/components/BackIcon.vue')['default']
  const BaseButton: typeof import('./src/components/BaseButton.vue')['default']
  const BaseIcon: typeof import('./src/components/BaseIcon.vue')['default']
  const BaseInput: typeof import('./src/components/base/BaseInput.vue')['default']
  const BasePage: typeof import('./src/components/BasePage.vue')['default']
  const Book: typeof import('./src/components/Book.vue')['default']
  const Checkbox: typeof import('./src/components/base/checkbox/Checkbox.vue')['default']
  const Close: typeof import('./src/components/icon/Close.vue')['default']
  const DictGroup: typeof import('./src/components/list/DictGroup.vue')['default']
  const DictList: typeof import('./src/components/list/DictList.vue')['default']
  const Empty: typeof import('./src/components/Empty.vue')['default']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const IconEosIconsLoading: typeof import('~icons/eos-icons/loading')['default']
  const IconFluentAdd16Regular: typeof import('~icons/fluent/add16-regular')['default']
  const IconFluentArrowCircleRight16Regular: typeof import('~icons/fluent/arrow-circle-right16-regular')['default']
  const IconFluentArrowShuffle20Filled: typeof import('~icons/fluent/arrow-shuffle20-filled')['default']
  const IconFluentArrowSwap20Regular: typeof import('~icons/fluent/arrow-swap20-regular')['default']
  const IconFluentBookNumber20Filled: typeof import('~icons/fluent/book-number20-filled')['default']
  const IconFluentCheckmarkCircle20Filled: typeof import('~icons/fluent/checkmark-circle20-filled')['default']
  const IconFluentChevronLeft28Filled: typeof import('~icons/fluent/chevron-left28-filled')['default']
  const IconFluentDismissCircle16Regular: typeof import('~icons/fluent/dismiss-circle16-regular')['default']
  const IconFluentDismissCircle20Filled: typeof import('~icons/fluent/dismiss-circle20-filled')['default']
  const IconFluentErrorCircle20Filled: typeof import('~icons/fluent/error-circle20-filled')['default']
  const IconFluentEye16Regular: typeof import('~icons/fluent/eye16-regular')['default']
  const IconFluentEyeOff16Regular: typeof import('~icons/fluent/eye-off16-regular')['default']
  const IconFluentLockClosed20Regular: typeof import('~icons/fluent/lock-closed20-regular')['default']
  const IconFluentMail20Regular: typeof import('~icons/fluent/mail20-regular')['default']
  const IconFluentNumberSymbol20Regular: typeof import('~icons/fluent/number-symbol20-regular')['default']
  const IconFluentPhone20Regular: typeof import('~icons/fluent/phone20-regular')['default']
  const IconFluentSearch24Regular: typeof import('~icons/fluent/search24-regular')['default']
  const IconFluentSlideTextTitleEdit20Regular: typeof import('~icons/fluent/slide-text-title-edit20-regular')['default']
  const IconFluentStar20Filled: typeof import('~icons/fluent/star20-filled')['default']
  const Progress: typeof import('./src/components/base/Progress.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Toast: typeof import('./src/components/base/toast/Toast.vue')['default']
  const Tooltip: typeof import('./src/components/base/Tooltip.vue')['default']
}